close all
clear variables
%%
obj = setupSystemObjects();

%videoplayer=vision.VideoPlayer('Position', [20, 400, 700, 400]);
i=0;
% Auto-generated by cameraCalibrator app on 09-Apr-2021
%-------------------------------------------------------

writerObj = VideoWriter('myVideo2.avi');
writerObj.FrameRate = 25;
open(writerObj);
Distance = 0;

while hasFrame(obj.reader)
    image = readFrame(obj.reader);
    %image = (imread('C:\Timo Lempers\Masters\Image Processing\Project\project 2\blobAnalysis\examples\Screenshot.png')); %Reads the Image document
    %imshow(image);
 image2 = insertShape(image,'FilledRectangle', [0 0 2000 523],'Color',{'green'});
 image2 = insertShape(image2,'FilledRectangle', [0 0 655+i/2 2000],'Color',{'green'});
 image2 = insertShape(image2,'FilledRectangle', [1062 0 500 2000],'Color',{'green'});
 image2 = insertShape(image2,'FilledRectangle', [0 551 2000 700],'Color',{'green'});  
 I = image2;

   channel1Min = 226.000;
channel1Max = 255.000;

% Define thresholds for channel 2 based on histogram settings
channel2Min = 227.000;
channel2Max = 255.000;

% Define thresholds for channel 3 based on histogram settings
channel3Min = 227.000;
channel3Max = 255.000;

    % Create mask based on chosen histogram thresholds
    sliderBW = (I(:,:,1) >= channel1Min ) & (I(:,:,1) <= channel1Max) & ...
        (I(:,:,2) >= channel2Min ) & (I(:,:,2) <= channel2Max) & ...
        (I(:,:,3) >= channel3Min ) & (I(:,:,3) <= channel3Max);

    %subplot(1,3,2)
    %imshow(sliderBW)


HorizonLine = 535;
    hBlobAnalysis = vision.BlobAnalysis('MinimumBlobArea' , 1, ...
        'MaximumBlobArea',5, 'MaximumCount', 1);
    [objArea, objCentroid,bboxOut] = step(hBlobAnalysis,sliderBW);
TF = isempty(bboxOut);
if TF == 0
    delta = (sqrt(0.98*2.5))/60; 
buoypos = bboxOut(1,2);
difference = buoypos-515;
focallength = 1.675213074929131e+03;
gamma = atand(double(difference)/focallength);

beta = 90-gamma-delta;

R=6371000;
h=2.5;
d = (R+h)*cosd(beta)-sqrt((R+h)^2*(cosd(beta)^2)-(R+h)^2+R^2);
Distance = 1;
end

    Ishape = insertShape(image2, 'rectangle',bboxOut,'Linewidth',4);
if Distance == 0
    Ishape = insertText(Ishape, [100 100],"No Buoy Found", 'FontSize', 24);
end
if Distance == 1
    Ishape = insertText(Ishape, [100 100],d, 'FontSize', 24);

end
%a = bboxOut(1,2);
    %figure
    %subplot(1,2,1)
    %imshow(Ishape)
    release(hBlobAnalysis);
    imwrite(Ishape,strcat('image',int2str(i),'.png'));
    frame=imread(strcat('image',int2str(i),'.png'));
    frame=im2frame(frame);
    writeVideo(writerObj, frame);
    %delete(Ishape,strcat('image',int2str(i),'.png'))
    i=i+1;
end
close(writerObj);

function obj = setupSystemObjects()
        % Initialize Video I/O
        % Create objects for reading a video from a file, drawing the tracked
        % objects in each frame, and playing the video.
        obj.reader = VideoReader('StabilizedVideo.avi');

        obj.videoFWriter=vision.VideoFileWriter('result3.avi');
end